# Analyzer options:
#   https://www.dartlang.org/guides/language/analysis-options
#
analyzer:
  strong-mode: true

  exclude:
    # Dart I
    - lib
    - off
    - test

    - lib/_templates/**
    - tool/demobase/**
    - tool/jsbase/**
    - tool/portbase/**
    - tool/templates/**
    - tool/templates/**

    # Exclude test because of https://github.com/dart-lang/sdk/issues/26420
    # and https://github.com/dart-lang/test/issues/436
    - test/**


