// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'package:dryice/dryice.dart' as prefix0;
import 'package:mdl/mdlcore.dart' as prefix1;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.InjectAnnotation(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"MaterialApplication",
            r"mdlcore.MaterialApplication",
            7,
            0,
            const prefix0.InjectAnnotation(),
            const <int>[0, 1],
            const <int>[2, 3, 4, 5, 6, 0],
            const <int>[],
            -1,
            {},
            {},
            {r"": (b) => () => b ? new prefix1.MaterialApplication() : null},
            0,
            0,
            const <int>[],
            const <Object>[prefix0.inject],
            null)
      ],
      <m.DeclarationMirror>[
        new r.MethodMirrorImpl(r"run", 262146, 0, null, -1, -1, const <int>[],
            const prefix0.InjectAnnotation(), const <Object>[]),
        new r.MethodMirrorImpl(r"", 64, 0, -1, 0, 0, const <int>[],
            const prefix0.InjectAnnotation(), const []),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, 1, 1, const <int>[0],
            const prefix0.InjectAnnotation(), const <Object>[]),
        new r.MethodMirrorImpl(r"toString", 131074, null, -1, 2, 2,
            const <int>[], const prefix0.InjectAnnotation(), const <Object>[]),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, null, null,
            const <int>[1], const prefix0.InjectAnnotation(), const <Object>[]),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, 3, 3,
            const <int>[], const prefix0.InjectAnnotation(), const <Object>[]),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, 4, 4,
            const <int>[], const prefix0.InjectAnnotation(), const <Object>[])
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(
            r"other",
            16390,
            2,
            const prefix0.InjectAnnotation(),
            null,
            null,
            null,
            const <Object>[],
            null,
            null),
        new r.ParameterMirrorImpl(
            r"invocation",
            32774,
            4,
            const prefix0.InjectAnnotation(),
            -1,
            5,
            5,
            const <Object>[],
            null,
            null)
      ],
      <Type>[prefix1.MaterialApplication, bool, String, int, Type, Invocation],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"run": (dynamic instance) => instance.run
      },
      {},
      <m.LibraryMirror>[
        new r.LibraryMirrorImpl(
            r"mdlcore",
            Uri.parse(r"reflectable://0/mdlcore"),
            const prefix0.InjectAnnotation(),
            const <int>[],
            {},
            {},
            const <Object>[],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
